name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd api && docker build . --file Dockerfile --tag samuelcunha/flask-api
      
    - uses: actions/checkout@v3
    - name: Publish the Docker image
      run: docker push samuelcunha/flask-api
